### ISSUE TITLE
Strange error 

### ISSUE THREAD

**Issue by sewek333** [ethaniccc/Mockingbird#112]
Ever since I use this plugin throws me players because of "logged out due to NetworkS
tackLatency timeout (bad connection?) - Rejoin server"
How do I turn it off?

**Comment by ethaniccc** [comment]
This is a known issue and I'm trying to look for better solutions to no response in packets

This feature was put in place as a safegaurd against ignoring a certain packet, which will lead to Mockingbird being bypassed - there is no way to turn this off *as of now*.

**Comment by UnEnanoMas** [comment]
Tip for the writer of the report:

Disable all BadPacket settings, players can play "more often" than before, before when they entered they were disconnected, if you disable all those, they can play for a long time

**Comment by sewek333** [comment]
@UnEnanoMas How do I turn it off?

**Comment by UnEnanoMas** [comment]
```
# BadPackets
BadPacketA:
  # this checks is the pitch the client gives is valid
  enabled: false
  punish: true
  punishment_type: ban
  max_violations: 1
BadPacketB:
  # this checks if the player consistently sends MovePlayerPackets,
  # which is impossible because isMovementServerAuthoritative is set to true in the StartGamePacket
  # reference: https://github.com/Sandertv/gophertunnel/blob/master/minecraft/protocol/packet/player_auth_input.go#L56-L59
  enabled: false
  punish: true
  punishment_type: kick
  max_violations: 20
BadPacketC:
  # checks if the player is attacking themselves (not projectile) - completely invalid
  enabled: false
  punish: true
  punishment_type: kick
  max_violations: 2
BadPacketD:
  # checks if the user is gliding without an elytra
  enabled: true
  punish: true
  punishment_type: kick
  max_violations: 5
BadPacketE:
  # checks for invalid deltas in a movement packet
  enabled: false
  punish: true
  punishment_type: kick
  max_violations: 10
BadPacketF:
  enabled: false
  punish: true
  punishment_type: kick
  max_violations: 5
  ```
  
  @sewek333 set all "enabled: false"
